spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://database:3306/erient 
    username: root
    password: changeitpls
    driver-class-name: com.mysql.jdbc.Driver
    
youtube:
  apiKey: enterKeyHere
  userId: putyouridhere
  password: putyourpasswordhere
project:
  name: eri-ent-project
  version: dev